# Generated by Django 4.2.6 on 2023-11-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0002_remove_cpe__product_remove_module__product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CveIngestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("valid_to", models.DateField()),
                ("delta", models.BooleanField(default=True)),
            ],
        ),
    ]
