# Generated by Django 4.2.6 on 2023-11-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0003_cveingestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="cverecord",
            name="triaged",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="cverecord",
            index=models.Index(fields=["cve_id"], name="shared_cver_cve_id_03da30_idx"),
        ),
    ]
