# Generated by Django 4.2.6 on 2023-11-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0004_cverecord_triaged_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NixChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("supported", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="NixMaintainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name="cverecord",
            name="triaged",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="NixPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=128)),
                ("long_description", models.TextField()),
                ("homepage", models.CharField(max_length=1024)),
                ("license", models.CharField(max_length=128)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.nixchannel",
                    ),
                ),
                ("maintainers", models.ManyToManyField(to="shared.nixmaintainer")),
            ],
        ),
        migrations.CreateModel(
            name="NixChannelResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=40)),
                ("result", models.FileField(upload_to="")),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.nixchannel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="nixissue",
            name="affected_packages",
            field=models.ManyToManyField(to="shared.nixpackage"),
        ),
    ]
