# Generated by Django 4.2.6 on 2023-11-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0005_nixchannel_nixmaintainer_alter_cverecord_triaged_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NixStoreHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("out_path", models.CharField(max_length=256)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.nixpackage",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.nixchannelresult",
                    ),
                ),
            ],
        ),
    ]
